# Generated by Django 4.0.1 on 2022-01-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=20)),
                ('voti', models.IntegerField(max_length=2)),
            ],
        ),
    ]
